// ignore_for_file: avoid_print

import 'dart:io';

import 'package:googleapis/sheets/v4.dart' as sheets;
import 'package:googleapis_auth/auth_io.dart';

/// Pulls distinct values from a sheet column, groups them by word-set
/// (case-insensitive, order- and multiplicity-insensitive on individual words),
/// and prints both:
///   - the consolidated canonical list (most-used variant wins per group)
///   - the merge map (variant → canonical) for any group with >1 variant
///
/// Defaults match the fitness-logger Strength Tracker.Exercise column.
Future<void> main(List<String> args) async {
  final spreadsheetId = args.isNotEmpty
      ? args[0]
      : '1BqV635hjq0XN9tTjVtH_Y6kI-NfPI1rdEvALtFlM7Nk';
  final tab = args.length > 1 ? args[1] : 'Strength Tracker';
  final columnHeader = args.length > 2 ? args[2] : 'Exercise';

  final home = Platform.environment['HOME']!;
  final keyJson = await File(
    '$home/.config/ledger/service-account.json',
  ).readAsString();
  final credentials = ServiceAccountCredentials.fromJson(keyJson);
  final client = await clientViaServiceAccount(
    credentials,
    [sheets.SheetsApi.spreadsheetsScope],
  );
  final api = sheets.SheetsApi(client);
  final resp = await api.spreadsheets.values.get(spreadsheetId, "'$tab'");
  final values = resp.values ?? [];
  if (values.isEmpty) {
    print('empty sheet');
    exit(1);
  }
  final headers = values.first.map((e) => e.toString()).toList();
  final col = headers.indexOf(columnHeader);
  if (col < 0) {
    print('no column "$columnHeader" in $headers');
    exit(1);
  }
  final counts = <String, int>{};
  for (var i = 1; i < values.length; i++) {
    final row = values[i];
    if (row.length <= col) continue;
    final v = row[col].toString().trim().replaceAll(RegExp(r'\s+'), ' ');
    if (v.isEmpty) continue;
    counts[v] = (counts[v] ?? 0) + 1;
  }

  final groups = <String, List<MapEntry<String, int>>>{};
  for (final e in counts.entries) {
    final key = _wordSetKey(e.key);
    groups.putIfAbsent(key, () => []).add(e);
  }

  final merges = <String, String>{}; // variant -> canonical
  final canonicals = <MapEntry<String, int>>[];
  for (final group in groups.values) {
    group.sort((a, b) => b.value.compareTo(a.value));
    final canonical = group.first;
    var groupTotal = 0;
    for (final e in group) {
      groupTotal += e.value;
      if (e.key != canonical.key) merges[e.key] = canonical.key;
    }
    canonicals.add(MapEntry(canonical.key, groupTotal));
  }
  canonicals.sort((a, b) => b.value.compareTo(a.value));

  print('=== merges (${merges.length}) ===');
  final byCanonical = <String, List<String>>{};
  for (final e in merges.entries) {
    byCanonical.putIfAbsent(e.value, () => []).add(e.key);
  }
  for (final c in byCanonical.keys) {
    print('$c');
    for (final v in byCanonical[c]!) {
      print('  ← $v');
    }
  }

  print('\n=== canonical exercises (${canonicals.length}) ===');
  for (final e in canonicals) {
    print('${e.value.toString().padLeft(4)}  ${e.key}');
  }

  // Emit YAML samples block for easy paste into strength.view.yml
  final yamlPath = 'tool/exercises.samples.yml';
  final buf = StringBuffer();
  buf.writeln('# Generated by tool/consolidate_exercises.dart');
  buf.writeln('# ${canonicals.length} canonical exercises, sorted by frequency');
  buf.writeln('samples:');
  for (final e in canonicals) {
    final escaped = e.key.contains(':') || e.key.contains('#')
        ? '"${e.key.replaceAll('"', r'\"')}"'
        : e.key;
    buf.writeln('  - $escaped');
  }
  await File(yamlPath).writeAsString(buf.toString());
  print('\nwrote $yamlPath');
  exit(0);
}

/// Word-set key: lowercase, split on whitespace + punctuation, ignore
/// duplicates, sort. Treats "Barbell Close Grip Bench Press" and
/// "Close Grip Barbell Bench Press" as the same exercise.
String _wordSetKey(String s) {
  final words = s
      .toLowerCase()
      .split(RegExp(r'[\s\-_/.,()]+'))
      .where((w) => w.isNotEmpty)
      .toSet()
      .toList()
    ..sort();
  return words.join('|');
}
